#!/usr/bin/env bash
#Let’s install the ufw firewall and accept traffics from port 80,443, and 22

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
