#!/usr/bin/env bash
NGINX_CONFIG="/etc/nginx/sites-available/default"

if ! grep -q "location /redirect_me" "$NGINX_CONFIG"; then
    sudo sed -i 's|\(server_name _;\)|\1\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }|' "$NGINX_CONFIG"
fi

sudo nginx -t && sudo systemctl reload nginx
