#!/usr/bin/env bash
# Configure nginx server redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
replacement_line="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$replacement_line/" /etc/nginx/sites-available/default
sudo service nginx restart
